# Práctica 1.2 — Probabilidad y Estadística
## Análisis de la evolución poblacional mundial

In [5]:
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

In [22]:
df.head(3)

                  Pais  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138

In [13]:
df.columns.to_list()
##Renombrar columnas
df.rename(columns={"entity": "Pais"}, inplace=True)

In [ ]:
df.set_index("code","year")
##Utiliza el lugar de una columna en lugar del id

                  Pais  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138

In [21]:
df.head(3)

                  Pais  life_expectancy_0
code year
AFG  1950  Afghanistan            28.1563
     1951  Afghanistan            28.5836
     1952  Afghanistan            29.0138

In [24]:
df.loc[df("code").isnull()]

TypeError: 'DataFrame' object is not callable

In [ ]:

df.loc[df["code"].notnull(),["entity","year","life_expectancy_0"]].head()

        entity  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138
3  Afghanistan  1953            29.4521
4  Afghanistan  1954            29.6975